### ISSUE TITLE
This already exists

### ISSUE THREAD

**Issue by WimTenBrink** [g1f1/HelloWorld#2]
See http://helloworldcollection.de/ for a list of many, many programming languages saying "Hello, World!"

**Comment by g1f1** [comment]
But it does not exist as a repository and I want to use it in laboratories..

**Comment by g1f1** [comment]
> See http://helloworldcollection.de/ for a list of many, many programming languages saying "Hello, World!"

But it does not exist as a repository and I want to use it in laboratories..
